wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/image_encoder_hiera_t.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/prompt_encoder_hiera_t.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/mask_decoder_hiera_t.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/mlp_hiera_t.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/memory_encoder_hiera_t.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/memory_attention_hiera_t.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/image_encoder_hiera_t_512.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/prompt_encoder_hiera_t_512.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/mask_decoder_hiera_t_512.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/mlp_hiera_t_512.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/memory_encoder_hiera_t_512.tflite -P ./model/
wget https://storage.googleapis.com/ailia-models-tflite/segment-anything-2/memory_attention_hiera_t_512.tflite -P ./model/